### ISSUE TITLE
Not possible to install on Windows?

### ISSUE THREAD

**Issue by knuthnads** [zzzyuqing/DreamMat#15]
Having a hard time trying to get this to install on Windows 10.

The [raytracing](https://github.com/ashawkey/raytracing) module fails to install:

`fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory`

I've tried the [secantalpha fork](https://github.com/secantalpha/raytracing) but this also fails:

`fatal error C1083: Cannot open include file: 'eigen/matrix.h': No such file or directory`

I'm completely stuck because of these eigen issues. Not sure what to do here.

**Comment by XZYW7** [comment]
It seems still caused by the Eigen path or environment. `raytracing` will automatically search and install Eigen. I recommend manually install raytracing and check `find_eigen()` result in `setup.py`. I have installed it successfully on windows 10. And I found that the `find_eigen()` result is not the path of auto installed Eigen. Maybe it should be modified in `find_eigen()` or installing eigen at the corresponding path if you also have the problem.

**Comment by knuthnads** [comment]
Oh it's finding eigen alright.

Regarding the eigen/matrix.h error, in /lib/site-packages/torch/include/pybind11/eigen.h if I change:

`#include "eigen/matrix.h"`

to:

`#include "eigen/src/Core/matrix.h"`

it finds the matrix.h file finally. However when I try installing the raytracing module manually it now fails with:

```
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(18): error C3856: 'traits': symbol is not a class template
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(18): error C2146: syntax error: missing ';' before identifier 'Matrix'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(18): error C2143: syntax error: missing ';' before '<'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(18): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(19): error C2143: syntax error: missing ';' before '{'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(19): error C2447: '{': missing function header (old-style formal list?)
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(179): error C2143: syntax error: missing ',' before '<'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(450): note: see reference to class template instantiation 'Eigen::Matrix<_Scalar,_Rows,_Cols,_Options,_MaxRows,_MaxCols>' being compiled
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(186): error C2143: syntax error: missing ';' before '<'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(186): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(186): error C2238: unexpected token(s) preceding ';'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(192): error C2653: 'Base': is not a class or namespace name
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(192): error C2144: syntax error: 'int' should be preceded by ';'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(192): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(192): warning C4183: 'EIGEN_DENSE_PUBLIC_INTERFACE': missing return type; assumed to be a member function returning 'int'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(192): error C3646: 'PlainObject': unknown override specifier
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(194): error C2653: 'Base': is not a class or namespace name
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(195): error C2653: 'Base': is not a class or namespace name
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(206): error C3646: 'EIGEN_STRONG_INLINE': unknown override specifier
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(206): error C3646: 'Matrix': unknown override specifier
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(206): error C2143: syntax error: missing ';' before '&'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(206): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(207): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(223): error C2061: syntax error: identifier 'EIGEN_STRONG_INLINE'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(224): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(236): error C2061: syntax error: identifier 'EIGEN_STRONG_INLINE'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(237): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(243): error C2061: syntax error: identifier 'EIGEN_STRONG_INLINE'
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(244): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(258): error C3646: 'EIGEN_STRONG_INLINE': unknown override specifier
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(259): error C3646: 'Matrix': unknown override specifier
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(259): error C2988: unrecognizable template declaration/definition
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(259): error C2059: syntax error: '('
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(259): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
C:/Program Files/Eigen3/include/eigen3\eigen/src/Core/matrix.h(14): fatal error C1075: '{': no matching token found
```

I honestly have no idea what you did to install eigen properly in Windows. This just seems like a complete mess.

**Comment by XZYW7** [comment]
It seems that the change you did 
`#include "eigen/matrix.h"`
to:
`#include "eigen/src/Core/matrix.h"`  caused the errors above. 
`"eigen/matrix.h"` should be the local file in [pybind11](https://github.com/pybind/pybind11/blob/master/include/pybind11/eigen/matrix.h). 
And it seems we are in different torch environment. I'm using troch-2.0.0-cu118 so there is no code `#include "eigen/matrix.h"` in  /lib/site-packages/torch/include/pybind11/eigen.h. Maybe you are using a newer version. And I have found a [solution](https://github.com/ashawkey/cubvh/issues/11) to the missing of `'eigen/matrix.h'`. Hope it works for you.

**Comment by knuthnads** [comment]
I was able to get the raytracer to install by adding

`#include "eigen/eigenvalues"`

in /Lib/site-packages/torch/include/pybind11/eigen.h before

`#include "eigen/src/Core/matrix.h"`

Unfortunately ran into more raytracer-related problems when trying to run run_examples.sh:

```
(venv)
knuthnads@knuthnads-PC MINGW64 /d/Projects/Python/DreamMat/threestudio_dreammat (main)
$ sh cmd/run_examples.sh
Seed set to 0
D:\Projects\Python\DreamMat\venv\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
cuda:0
D:\Projects\Python\DreamMat\venv\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Using C:\Users\knuthnads\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\knuthnads\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu121\renderutils_plugin\build.ninja...
Building extension module renderutils_plugin...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module renderutils_plugin...
EnvProbe, torch.Size([2048, 4096, 3]) , min/max 0.07114315032958984 70.25756072998047
EnvProbe, torch.Size([2048, 4096, 3]) , min/max 0.00439453125 36.5
EnvProbe, torch.Size([2048, 4096, 3]) , min/max 0.002166748046875 117.5
EnvProbe, torch.Size([2048, 4096, 3]) , min/max 0.0 370.0
EnvProbe, torch.Size([2048, 4096, 3]) , min/max 0.0 17.375
Traceback (most recent call last):
  File "D:\Projects\Python\DreamMat\threestudio_dreammat\launch.py", line 244, in <module>
    main(args, extras)
  File "D:\Projects\Python\DreamMat\threestudio_dreammat\launch.py", line 105, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "D:\Projects\Python\DreamMat\threestudio_dreammat\threestudio\systems\base.py", line 45, in __init__
    self.configure()
  File "D:\Projects\Python\DreamMat\threestudio_dreammat\threestudio\systems\dreammat.py", line 36, in configure
    super().configure()
  File "D:\Projects\Python\DreamMat\threestudio_dreammat\threestudio\systems\base.py", line 290, in configure
    self.renderer = threestudio.find(self.cfg.renderer_type)(
  File "D:\Projects\Python\DreamMat\threestudio_dreammat\threestudio\utils\base.py", line 102, in __init__
    self.configure(*args, **kwargs)
  File "D:\Projects\Python\DreamMat\threestudio_dreammat\threestudio\models\renderers\raytracing_renderer.py", line 103, in configure
    self.ray_tracer = RayTracer(self.mesh.v_pos, self.mesh.t_pos_idx)
  File "D:\Projects\Python\DreamMat\threestudio_dreammat\threestudio\models\renderers\raytracing_renderer.py", line 31, in __init__
    self.impl = _backend.create_raytracer(vertices, triangles)
TypeError: create_raytracer(): incompatible function arguments. The following argument types are supported:
    1. (arg0: Eigen::Ref<Eigen::Matrix<float,-1,3,1,-1,3> const ,0,Eigen::OuterStride<-1> >, arg1: Eigen::Ref<Eigen::Matrix<unsigned int,-1,3,1,-1,3> const ,0,Eigen::OuterStride<-1> >) -> _raytracing.RayTracer

Invoked with: array([[ 0.22140308, -0.09450536, -0.5365572 ],
       [ 0.22140308, -0.09450536, -0.5365572 ],
       [ 0.20678934, -0.10736789, -0.51840633],
       ...,
       [-0.02723045, -0.2844407 , -0.15166304],
       [ 0.02945502, -0.29194534, -0.1176769 ],
       [-0.02523098, -0.28556624, -0.15570337]], dtype=float32), array([[    0,     2,     3],
       [    2,     5,     3],
       [    7,     8,     9],
       ...,
       [54443, 54829, 54552],
       [54412, 54874, 54390],
       [54413, 54502, 54414]], dtype=int64)
```
Tried again with CUDA 11.8/pytorch 2.0.0. Just getting a flood of errors like:

```
C:\Program Files\Eigen3\include\eigen3\Eigen\src/Core/util/DisableStupidWarnings.h(77): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

C:\Program Files\Eigen3\include\eigen3\Eigen\src/Core/util/DisableStupidWarnings.h(83): warning C4068: unknown pragma 'diag_suppress'
```

I think I'm done trying to get this to run on Windows. It's just impossible due to the raytracing module. Seems like interesting technology, for what it's worth.

**Comment by XZYW7** [comment]
The [secantalpha fork](https://github.com/secantalpha/raytracing) uses Eigen-4.0.0 in Windows 10(CUDA 12.1, python 3.10, pytorch 2.3). An in the environment of CUDA 11.8/pytorch 2.0.0, I run it with Eigen-3.3.9. I'm not sure if the Eigen version should match with CUDA and torch version. But you can try it.
