### ISSUE TITLE
Unable to run in docker container 

### ISSUE THREAD

**Issue by gurudt12** [zzzyuqing/DreamMat#16]
Facing this issue when I am running gradio UI 

Traceback (most recent call last):
  File "/workspace/DreamMat/threestudio_dreammat/gradio_app.py", line 90, in <module>
    with open(config_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/gradio/sjc.yaml'

Also, when running examples, I am facing another issue

[ WARN:0@26.351] global loadsave.cpp:241 findDecoder imread_('outputs/dream_mat/A_natural_grey_rabbit/pre_render/depth/000.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/workspace/DreamMat/threestudio_dreammat/launch.py", line 244, in <module>
    main(args, extras)
  File "/workspace/DreamMat/threestudio_dreammat/launch.py", line 189, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 949, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/workspace/DreamMat/threestudio_dreammat/threestudio/data/uncond.py", line 963, in setup
    self.train_dataset = FixCameraIterableDataset(self.cfg,self.mesh,self.prerender_dir)
  File "/workspace/DreamMat/threestudio_dreammat/threestudio/data/uncond.py", line 705, in __init__
    self.render_fixview_imgs()
  File "/workspace/DreamMat/threestudio_dreammat/threestudio/data/uncond.py", line 566, in render_fixview_imgs
    self.depths[view_idx] = torch.from_numpy(loaddepth(depth_path, dim))
  File "/workspace/DreamMat/threestudio_dreammat/threestudio/data/uncond.py", line 541, in loaddepth
    depth = cv2.imread(imgpath, cv2.IMREAD_ANYDEPTH)/1000
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

Can you please let me know steps to follow when I am running Dreamt via Docker 

docker image : zzzyuqing/dreammat_image   v1.0

**Comment by gurudt12** [comment]
Also, Does this method create texture for original mesh or it creates a mesh of its own

**Comment by zzzyuqing** [comment]
1. DreamMat is designed to generate textures for the original mesh.
2. Currently, DreamMat doesn't support Gradio. You can run it using **`sh cmd/run_examples.sh`**.
3. The **`TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'`** error might be due to Blender not rendering the condition images. Please ensure Blender is installed. You can find the installation steps in the README.

Hope this helps!
